-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE IF NOT EXISTS join_applications (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 name TEXT NOT NULL,
 email TEXT NOT NULL,
 student_id TEXT,
 major TEXT NOT NULL,
 year_of_study TEXT NOT NULL,
 interest_role TEXT NOT NULL,
 experience TEXT,
 why_join TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE join_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_insert_join_applications ON join_applications
 FOR INSERT
 WITH CHECK (true);

