/**
 * 🚨 此文件由 Meoo Cloud 自动生成，请勿手动修改！
 * This file is auto-generated by Meoo Cloud. Do not edit manually!
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export function getSupabaseUrl(): string {
  return `${(window as any).MEOO_CONFIG?.meoo_app_access_url || window.location.origin}/sb-api`;
}

export const supabaseUrl = getSupabaseUrl();
export const supabaseAnonKey = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzg1NTEyNDE5LCJleHAiOjEzMjk2MTUyNDE5fQ.Wl-KdEBoBE3u4K5ueQ6DHtGTapTisO3GgAWibiw0dtc";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  },
});
