/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as JoinRouteImport } from './routes/join'
import { Route as RoadRouteImport } from './routes/road'
import { Route as RobotRouteImport } from './routes/robot'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutAwardsRouteImport } from './routes/about.awards'
import { Route as AboutSustainabilityRouteImport } from './routes/about.sustainability'
import { Route as AboutTeamRouteImport } from './routes/about.team'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyMechanicalRouteImport } from './routes/academy.mechanical'
import { Route as AcademyProgrammingRouteImport } from './routes/academy.programming'
import { Route as AcademyResourcesRouteImport } from './routes/academy.resources'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadRoute = RoadRouteImport.update({
  id: '/road',
  path: '/road',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotRoute = RobotRouteImport.update({
  id: '/robot',
  path: '/robot',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutAwardsRoute = AboutAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AboutRoute,
} as any)
const AboutSustainabilityRoute = AboutSustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => AboutRoute,
} as any)
const AboutTeamRoute = AboutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AboutRoute,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyMechanicalRoute = AcademyMechanicalRouteImport.update({
  id: '/mechanical',
  path: '/mechanical',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyProgrammingRoute = AcademyProgrammingRouteImport.update({
  id: '/programming',
  path: '/programming',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyResourcesRoute = AcademyResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AcademyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/academy': typeof AcademyRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/road': typeof RoadRoute
  '/robot': typeof RobotRoute
  '/sponsors': typeof SponsorsRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/about/team': typeof AboutTeamRoute
  '/academy/mechanical': typeof AcademyMechanicalRoute
  '/academy/programming': typeof AcademyProgrammingRoute
  '/academy/resources': typeof AcademyResourcesRoute
  '/about/': typeof AboutIndexRoute
  '/academy/': typeof AcademyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/road': typeof RoadRoute
  '/robot': typeof RobotRoute
  '/sponsors': typeof SponsorsRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/about/team': typeof AboutTeamRoute
  '/academy/mechanical': typeof AcademyMechanicalRoute
  '/academy/programming': typeof AcademyProgrammingRoute
  '/academy/resources': typeof AcademyResourcesRoute
  '/about': typeof AboutIndexRoute
  '/academy': typeof AcademyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/academy': typeof AcademyRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/join': typeof JoinRoute
  '/road': typeof RoadRoute
  '/robot': typeof RobotRoute
  '/sponsors': typeof SponsorsRoute
  '/about/awards': typeof AboutAwardsRoute
  '/about/sustainability': typeof AboutSustainabilityRoute
  '/about/team': typeof AboutTeamRoute
  '/academy/mechanical': typeof AcademyMechanicalRoute
  '/academy/programming': typeof AcademyProgrammingRoute
  '/academy/resources': typeof AcademyResourcesRoute
  '/about/': typeof AboutIndexRoute
  '/academy/': typeof AcademyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/contact'
    | '/gallery'
    | '/join'
    | '/road'
    | '/robot'
    | '/sponsors'
    | '/about/awards'
    | '/about/sustainability'
    | '/about/team'
    | '/academy/mechanical'
    | '/academy/programming'
    | '/academy/resources'
    | '/about/'
    | '/academy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/join'
    | '/road'
    | '/robot'
    | '/sponsors'
    | '/about/awards'
    | '/about/sustainability'
    | '/about/team'
    | '/academy/mechanical'
    | '/academy/programming'
    | '/academy/resources'
    | '/about'
    | '/academy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/contact'
    | '/gallery'
    | '/join'
    | '/road'
    | '/robot'
    | '/sponsors'
    | '/about/awards'
    | '/about/sustainability'
    | '/about/team'
    | '/academy/mechanical'
    | '/academy/programming'
    | '/academy/resources'
    | '/about/'
    | '/academy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AcademyRoute: typeof AcademyRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  JoinRoute: typeof JoinRoute
  RoadRoute: typeof RoadRoute
  RobotRoute: typeof RobotRoute
  SponsorsRoute: typeof SponsorsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/road': {
      id: '/road'
      path: '/road'
      fullPath: '/road'
      preLoaderRoute: typeof RoadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robot': {
      id: '/robot'
      path: '/robot'
      fullPath: '/robot'
      preLoaderRoute: typeof RobotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/awards': {
      id: '/about/awards'
      path: '/awards'
      fullPath: '/about/awards'
      preLoaderRoute: typeof AboutAwardsRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/sustainability': {
      id: '/about/sustainability'
      path: '/sustainability'
      fullPath: '/about/sustainability'
      preLoaderRoute: typeof AboutSustainabilityRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/team': {
      id: '/about/team'
      path: '/team'
      fullPath: '/about/team'
      preLoaderRoute: typeof AboutTeamRouteImport
      parentRoute: typeof AboutRoute
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/mechanical': {
      id: '/academy/mechanical'
      path: '/mechanical'
      fullPath: '/academy/mechanical'
      preLoaderRoute: typeof AcademyMechanicalRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/programming': {
      id: '/academy/programming'
      path: '/programming'
      fullPath: '/academy/programming'
      preLoaderRoute: typeof AcademyProgrammingRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/resources': {
      id: '/academy/resources'
      path: '/resources'
      fullPath: '/academy/resources'
      preLoaderRoute: typeof AcademyResourcesRouteImport
      parentRoute: typeof AcademyRoute
    }
  }
}

interface AboutRouteChildren {
  AboutAwardsRoute: typeof AboutAwardsRoute
  AboutSustainabilityRoute: typeof AboutSustainabilityRoute
  AboutTeamRoute: typeof AboutTeamRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutAwardsRoute: AboutAwardsRoute,
  AboutSustainabilityRoute: AboutSustainabilityRoute,
  AboutTeamRoute: AboutTeamRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AcademyRouteChildren {
  AcademyMechanicalRoute: typeof AcademyMechanicalRoute
  AcademyProgrammingRoute: typeof AcademyProgrammingRoute
  AcademyResourcesRoute: typeof AcademyResourcesRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyMechanicalRoute: AcademyMechanicalRoute,
  AcademyProgrammingRoute: AcademyProgrammingRoute,
  AcademyResourcesRoute: AcademyResourcesRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AcademyRoute: AcademyRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  JoinRoute: JoinRoute,
  RoadRoute: RoadRoute,
  RobotRoute: RobotRoute,
  SponsorsRoute: SponsorsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
